[build]
# This ensures rust-analyzer and other IDE tools properly recognize all test files

[alias]
# Add any useful cargo aliases here
test-core = "test --test mod core"
test-network = "test --test mod network"

[rust-analyzer]
# Configure rust-analyzer to recognize our test directory structure
checkOnSave.extraArgs = ["--tests"]
cargo.buildScripts.enable = true
procMacro.enable = true 